// <auto-generated />
using System;
using Company_Management_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Company_Management_System.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20251011151010_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Company_Management_System.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ContractNumber")
                        .IsUnique();

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("contract");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContractNumber = "1001",
                            EmployeeId = 1,
                            EndDate = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 15000m,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            ContractNumber = "1002",
                            EmployeeId = 2,
                            EndDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 12000m,
                            StartDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            ContractNumber = "1003",
                            EmployeeId = 3,
                            EndDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 18000m,
                            StartDate = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            ContractNumber = "1004",
                            EmployeeId = 4,
                            EndDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 10000m,
                            StartDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Company_Management_System.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("department");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Giza",
                            Name = "Backend"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Cairo",
                            Name = "Frontend"
                        },
                        new
                        {
                            Id = 3,
                            Location = "Alexandria",
                            Name = "HR"
                        });
                });

            modelBuilder.Entity("Company_Management_System.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("employee");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Email = "adel@gmail.com",
                            Name = "Adel",
                            Phone = "01282768929"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            Email = "sara@gmail.com",
                            Name = "Sara",
                            Phone = "01125678945"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            Email = "omar@gmail.com",
                            Name = "Omar",
                            Phone = "01054789632"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 3,
                            Email = "nour@gmail.com",
                            Name = "Nour",
                            Phone = "01587456321"
                        });
                });

            modelBuilder.Entity("Company_Management_System.Models.EmployeeProject", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("employeeProject");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            ProjectId = 1
                        },
                        new
                        {
                            EmployeeId = 1,
                            ProjectId = 2
                        },
                        new
                        {
                            EmployeeId = 2,
                            ProjectId = 2
                        },
                        new
                        {
                            EmployeeId = 3,
                            ProjectId = 1
                        },
                        new
                        {
                            EmployeeId = 3,
                            ProjectId = 3
                        },
                        new
                        {
                            EmployeeId = 4,
                            ProjectId = 3
                        });
                });

            modelBuilder.Entity("Company_Management_System.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("project");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Budget = 5000m,
                            EndTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectName = "ManagementSystem",
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Budget = 15000m,
                            EndTime = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectName = "ECommercePlatform",
                            StartDate = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Budget = 8000m,
                            ProjectName = "MobileApp",
                            StartDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Company_Management_System.Models.Contract", b =>
                {
                    b.HasOne("Company_Management_System.Models.Employee", "employee")
                        .WithOne("contract")
                        .HasForeignKey("Company_Management_System.Models.Contract", "EmployeeId");

                    b.Navigation("employee");
                });

            modelBuilder.Entity("Company_Management_System.Models.Employee", b =>
                {
                    b.HasOne("Company_Management_System.Models.Department", "department")
                        .WithMany("employees")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("department");
                });

            modelBuilder.Entity("Company_Management_System.Models.EmployeeProject", b =>
                {
                    b.HasOne("Company_Management_System.Models.Employee", "employee")
                        .WithMany("projects")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Company_Management_System.Models.Project", "project")
                        .WithMany("employees")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("employee");

                    b.Navigation("project");
                });

            modelBuilder.Entity("Company_Management_System.Models.Department", b =>
                {
                    b.Navigation("employees");
                });

            modelBuilder.Entity("Company_Management_System.Models.Employee", b =>
                {
                    b.Navigation("contract");

                    b.Navigation("projects");
                });

            modelBuilder.Entity("Company_Management_System.Models.Project", b =>
                {
                    b.Navigation("employees");
                });
#pragma warning restore 612, 618
        }
    }
}
